import type {
  DailyReport,
  FetchAttempt,
  Opportunity,
  ReviewItem,
  Source,
} from "./types";

export const sources: Source[] = [
  {
    id: "src-github-campus",
    name: "GitHub Education Events",
    homepage: "https://github.com/education",
    adapterKey: "githubCampusAdapter",
    category: "hackathon",
    status: "active",
    robotsPolicy: "allowed",
    lastAttemptAt: "2026-06-27T08:30:00-07:00",
    owner: "platform",
  },
  {
    id: "src-yc",
    name: "Y Combinator Batch Companies",
    homepage: "https://www.ycombinator.com/companies",
    adapterKey: "ycBatchAdapter",
    category: "startup",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: "2026-06-27T08:22:00-07:00",
    lastFailureReason: "JavaScript-rendered company listings need a reviewed adapter before automated extraction.",
    owner: "platform",
  },
  {
    id: "src-linkedin",
    name: "LinkedIn Student Jobs",
    homepage: "https://www.linkedin.com/jobs/student-jobs",
    adapterKey: "linkedInAdapter",
    category: "mixed",
    status: "blocked",
    robotsPolicy: "restricted",
    lastAttemptAt: "2026-06-27T08:18:00-07:00",
    lastFailureReason: "Login and LinkedIn platform restrictions prevent compliant automated scraping.",
    owner: "legal-review",
  },
  {
    id: "src-nsf",
    name: "NSF Student Opportunities",
    homepage: "https://new.nsf.gov/careers",
    adapterKey: "nsfStudentAdapter",
    category: "fellowship",
    status: "active",
    robotsPolicy: "allowed",
    lastAttemptAt: "2026-06-27T08:12:00-07:00",
    owner: "platform",
  },
  {
    id: "src-x",
    name: "X Startup Announcements",
    homepage: "https://x.com",
    adapterKey: "xAnnouncementsAdapter",
    category: "startup",
    status: "blocked",
    robotsPolicy: "restricted",
    lastAttemptAt: "2026-06-27T08:06:00-07:00",
    lastFailureReason: "X restrictions and anti-bot protections require manual review or an approved API integration.",
    owner: "legal-review",
  },
];

export const attempts: FetchAttempt[] = [
  {
    id: "att-001",
    sourceId: "src-github-campus",
    attemptedAt: "2026-06-27T08:30:00-07:00",
    status: "success",
    recordsSeen: 4,
    recordsSaved: 2,
  },
  {
    id: "att-002",
    sourceId: "src-yc",
    attemptedAt: "2026-06-27T08:22:00-07:00",
    status: "manual_review_required",
    reason: "JavaScript-only rendering detected. No opportunity data was inferred.",
    recordsSeen: 0,
    recordsSaved: 0,
  },
  {
    id: "att-003",
    sourceId: "src-linkedin",
    attemptedAt: "2026-06-27T08:18:00-07:00",
    status: "blocked",
    reason: "Login requirement and platform restrictions.",
    recordsSeen: 0,
    recordsSaved: 0,
  },
  {
    id: "att-004",
    sourceId: "src-nsf",
    attemptedAt: "2026-06-27T08:12:00-07:00",
    status: "success",
    recordsSeen: 3,
    recordsSaved: 1,
  },
  {
    id: "att-005",
    sourceId: "src-x",
    attemptedAt: "2026-06-27T08:06:00-07:00",
    status: "blocked",
    reason: "Anti-bot protections and legal restrictions.",
    recordsSeen: 0,
    recordsSaved: 0,
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "opp-001",
    title: "Open Source Summer Maintainer Track",
    organization: "GitHub Education",
    type: "internship",
    status: "open",
    sourceId: "src-github-campus",
    location: "Remote",
    deadline: "2026-07-12",
    compensation: "$6,500 stipend",
    eligibility: "Students with merged open-source contributions",
    url: "https://github.com/education",
    discoveredAt: "2026-06-26T09:10:00-07:00",
    updatedAt: "2026-06-27T08:30:00-07:00",
    confidence: {
      source: 0.94,
      extraction: 0.91,
      freshness: 0.98,
      duplicateProbability: 0.08,
    },
    evidence: ["Title, deadline, and stipend confirmed from source text."],
    needsReview: false,
  },
  {
    id: "opp-002",
    title: "Civic Data Fellowship",
    organization: "National Science Foundation",
    type: "fellowship",
    status: "changed",
    sourceId: "src-nsf",
    location: "Arlington, VA or remote",
    deadline: "2026-07-26",
    compensation: "$1,250 weekly",
    eligibility: "Undergraduate and graduate students in data science, policy, or public interest technology",
    url: "https://new.nsf.gov/careers",
    discoveredAt: "2026-06-23T10:15:00-07:00",
    updatedAt: "2026-06-27T08:12:00-07:00",
    confidence: {
      source: 0.96,
      extraction: 0.86,
      freshness: 0.97,
      duplicateProbability: 0.14,
    },
    evidence: ["Deadline and compensation changed since the previous report."],
    needsReview: true,
  },
  {
    id: "opp-003",
    title: "Regional Student Builder Hackathon",
    organization: "Campus Builders Network",
    type: "hackathon",
    status: "open",
    sourceId: "src-github-campus",
    location: "San Jose, CA",
    deadline: "2026-07-03",
    compensation: "Travel grants available",
    eligibility: "High school seniors, college students, and recent graduates",
    url: "https://github.com/education",
    discoveredAt: "2026-06-27T08:30:00-07:00",
    updatedAt: "2026-06-27T08:30:00-07:00",
    confidence: {
      source: 0.88,
      extraction: 0.79,
      freshness: 0.99,
      duplicateProbability: 0.22,
    },
    evidence: ["Location and eligibility found; travel grant language is compensation-related evidence."],
    needsReview: true,
  },
  {
    id: "opp-004",
    title: "AI Research Co-op",
    organization: "Northstar Robotics",
    type: "co-op",
    status: "closed",
    sourceId: "src-yc",
    location: "Boston, MA",
    deadline: "2026-06-21",
    compensation: "Closed",
    eligibility: "Closed listing retained for report comparison",
    url: "https://www.ycombinator.com/companies",
    discoveredAt: "2026-06-14T13:00:00-07:00",
    updatedAt: "2026-06-26T15:00:00-07:00",
    confidence: {
      source: 0.62,
      extraction: 0.54,
      freshness: 0.52,
      duplicateProbability: 0.34,
    },
    evidence: ["Closure was confirmed in database history before today's blocked YC attempt."],
    needsReview: true,
  },
];

export const reviewQueue: ReviewItem[] = [
  {
    id: "rev-001",
    opportunityId: "opp-002",
    sourceId: "src-nsf",
    status: "pending",
    reason: "Compensation and eligibility changed; reviewer approval required before report export.",
    queuedAt: "2026-06-27T08:13:00-07:00",
    fields: {
      compensation: "$1,250 weekly",
      eligibility:
        "Undergraduate and graduate students in data science, policy, or public interest technology",
    },
    attachments: [
      { id: "file-001", kind: "screenshot", name: "nsf-compensation-change.png" },
    ],
    aiExtractionOverride: "Reviewer can replace compensation text before approval.",
  },
  {
    id: "rev-002",
    opportunityId: "opp-003",
    sourceId: "src-github-campus",
    status: "pending",
    reason: "Travel grant language may not be compensation. Needs human classification.",
    queuedAt: "2026-06-27T08:31:00-07:00",
    fields: {
      compensation: "Travel grants available",
    },
    attachments: [],
  },
  {
    id: "rev-003",
    sourceId: "src-linkedin",
    status: "pending",
    reason: "Source blocked by login and platform restrictions. Manual source review required.",
    queuedAt: "2026-06-27T08:18:00-07:00",
    fields: {},
    attachments: [],
  },
  {
    id: "rev-004",
    sourceId: "src-yc",
    status: "pending",
    reason: "YC source rendered with JavaScript-only content. Adapter produced no inferred records.",
    queuedAt: "2026-06-27T08:22:00-07:00",
    fields: {},
    attachments: [{ id: "file-002", kind: "screenshot", name: "yc-empty-render.png" }],
  },
];

export const report: DailyReport = {
  id: "rep-2026-06-27",
  date: "2026-06-27",
  week: "2026-W26",
  previousReportDate: "2026-06-26",
  previousReportWeek: "2026-W26",
  generatedFrom: "database",
  changes: [
    {
      id: "chg-001",
      kind: "new",
      opportunityId: "opp-003",
      title: "Regional Student Builder Hackathon",
      after: "New hackathon added from GitHub Education Events.",
    },
    {
      id: "chg-002",
      kind: "deadline_updated",
      opportunityId: "opp-002",
      title: "Civic Data Fellowship",
      before: "2026-07-19",
      after: "2026-07-26",
    },
    {
      id: "chg-003",
      kind: "compensation_updated",
      opportunityId: "opp-002",
      title: "Civic Data Fellowship",
      before: "$1,100 weekly",
      after: "$1,250 weekly",
    },
    {
      id: "chg-004",
      kind: "closed",
      opportunityId: "opp-004",
      title: "AI Research Co-op",
      before: "Open",
      after: "Closed",
    },
  ],
};
