import type {
  DailyReport,
  FetchAttempt,
  Opportunity,
  OpportunityType,
  ReviewItem,
  Source,
} from "./types";

const importedAt = "2026-06-28T10:15:00-07:00";
const chatImportEvidence =
  "Imported from shared ChatGPT conversation URL; official source still requires manual review.";
const officialEvidence =
  "Official destination URL was present in the shared conversation, but fields were not scraped live.";
const aggregatorEvidence =
  "Aggregator URL was present in the shared conversation; verify against the employer source before publishing.";

function candidate({
  id,
  title,
  organization,
  type,
  sourceId,
  url,
  location = "Manual review",
  eligibility,
  source = 0.84,
  extraction = 0.6,
  freshness = 0.72,
  duplicateProbability = 0.18,
  evidence = [chatImportEvidence, officialEvidence],
}: {
  id: string;
  title: string;
  organization: string;
  type: OpportunityType;
  sourceId: string;
  url: string;
  location?: string;
  eligibility: string;
  source?: number;
  extraction?: number;
  freshness?: number;
  duplicateProbability?: number;
  evidence?: string[];
}): Opportunity {
  return {
    id,
    title,
    organization,
    type,
    status: "open",
    sourceId,
    location,
    deadline: "Manual review",
    compensation: "Manual review",
    eligibility,
    url,
    discoveredAt: importedAt,
    updatedAt: importedAt,
    confidence: {
      source,
      extraction,
      freshness,
      duplicateProbability,
    },
    evidence,
    needsReview: true,
  };
}

export const sources: Source[] = [
  {
    id: "src-chatgpt-share",
    name: "Shared ChatGPT Conversation Import",
    homepage: "https://chatgpt.com/share/6a418ef2-e89c-83e8-9434-1af2bff1693",
    adapterKey: "chatGptShareImportAdapter",
    category: "mixed",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Conversation supplied candidate links only. The platform saved them as reviewable database records without inferring missing fields.",
    owner: "platform",
  },
  {
    id: "src-anthropic",
    name: "Anthropic Careers and Claude Corps",
    homepage: "https://www.anthropic.com/claude-corps/fellow",
    adapterKey: "anthropicCareerAdapter",
    category: "fellowship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Official links were imported from the conversation, but deadlines, compensation, and eligibility require source review.",
    owner: "platform",
  },
  {
    id: "src-apple-students",
    name: "Apple Student Jobs",
    homepage: "https://jobs.apple.com/en-us/search?team=STDNT",
    adapterKey: "appleStudentJobsAdapter",
    category: "internship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Apple student listings were imported as official URLs only. Structured field extraction is pending.",
    owner: "platform",
  },
  {
    id: "src-microsoft-students",
    name: "Microsoft Student Programs",
    homepage: "https://careers.microsoft.com/v2/global/en/students",
    adapterKey: "microsoftStudentsAdapter",
    category: "student-community",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Program landing page needs a reviewed adapter before automated opportunity extraction.",
    owner: "platform",
  },
  {
    id: "src-devpost",
    name: "Devpost Hackathons",
    homepage: "https://devpost.com/hackathons",
    adapterKey: "devpostHackathonAdapter",
    category: "hackathon",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Hackathon URLs were imported from the conversation. Dates, prizes, and eligibility are queued for manual verification.",
    owner: "platform",
  },
  {
    id: "src-nvidia",
    name: "NVIDIA Careers",
    homepage: "https://jobs.nvidia.com/careers",
    adapterKey: "nvidiaCareersAdapter",
    category: "internship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Role URL was imported without trusted structured details. Official page review is required.",
    owner: "platform",
  },
  {
    id: "src-cloudflare",
    name: "Cloudflare Careers and Early Talent",
    homepage: "https://www.cloudflare.com/careers/jobs/?department=Early+Talent",
    adapterKey: "cloudflareEarlyTalentAdapter",
    category: "internship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Early talent and Greenhouse links were imported, but individual role details need review.",
    owner: "platform",
  },
  {
    id: "src-samsara",
    name: "Samsara Careers",
    homepage: "https://www.samsara.com/company/careers/roles/7839203?gh_jid=7839203",
    adapterKey: "samsaraCareersAdapter",
    category: "internship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Role URL was imported without verified title, deadline, compensation, or eligibility.",
    owner: "platform",
  },
  {
    id: "src-mlh",
    name: "Major League Hacking Programs",
    homepage: "https://www.mlh.com/seasons/2026/events",
    adapterKey: "mlhProgramsAdapter",
    category: "hackathon",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "MLH links were imported from the conversation. Program terms and event dates need direct verification.",
    owner: "platform",
  },
  {
    id: "src-bebee",
    name: "BeBee Aggregator",
    homepage:
      "https://bebee.com/us/jobs/software-engineer-intern-spring-summer-2026-cohere-san-francisco-ca--theirstack-676643934",
    adapterKey: "bebeeAggregatorAdapter",
    category: "internship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Aggregator-only listing. Verify with Cohere or another official employer source before approval.",
    owner: "manual-review",
  },
  {
    id: "src-jobright",
    name: "Jobright Aggregator",
    homepage: "https://jobright.ai/jobs/info/69fecb6aae08e368e37a10c6",
    adapterKey: "jobrightAggregatorAdapter",
    category: "internship",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: importedAt,
    lastFailureReason:
      "Aggregator-only listing with unknown employer details. Manual review required before publication.",
    owner: "manual-review",
  },
  {
    id: "src-linkedin",
    name: "LinkedIn Student Jobs",
    homepage: "https://www.linkedin.com/jobs/student-jobs",
    adapterKey: "linkedInAdapter",
    category: "mixed",
    status: "blocked",
    robotsPolicy: "restricted",
    lastAttemptAt: "2026-06-27T08:18:00-07:00",
    lastFailureReason:
      "Login and LinkedIn platform restrictions prevent compliant automated scraping.",
    owner: "legal-review",
  },
  {
    id: "src-x",
    name: "X Startup Announcements",
    homepage: "https://x.com",
    adapterKey: "xAnnouncementsAdapter",
    category: "startup",
    status: "blocked",
    robotsPolicy: "restricted",
    lastAttemptAt: "2026-06-27T08:06:00-07:00",
    lastFailureReason:
      "X restrictions and anti-bot protections require manual review or an approved API integration.",
    owner: "legal-review",
  },
  {
    id: "src-yc",
    name: "Y Combinator Batch Companies",
    homepage: "https://www.ycombinator.com/companies",
    adapterKey: "ycBatchAdapter",
    category: "startup",
    status: "manual_review_required",
    robotsPolicy: "unknown",
    lastAttemptAt: "2026-06-27T08:22:00-07:00",
    lastFailureReason:
      "JavaScript-rendered company listings need a reviewed adapter before automated extraction.",
    owner: "platform",
  },
];

export const attempts: FetchAttempt[] = [
  {
    id: "att-chat-001",
    sourceId: "src-chatgpt-share",
    attemptedAt: importedAt,
    status: "manual_review_required",
    reason:
      "Shared conversation yielded candidate links. Saved as database records with review-required confidence, not verified scraped facts.",
    recordsSeen: 22,
    recordsSaved: 21,
  },
  {
    id: "att-anthropic-001",
    sourceId: "src-anthropic",
    attemptedAt: importedAt,
    status: "manual_review_required",
    reason: "Official Anthropic links imported; detailed extraction pending.",
    recordsSeen: 3,
    recordsSaved: 2,
  },
  {
    id: "att-apple-001",
    sourceId: "src-apple-students",
    attemptedAt: importedAt,
    status: "manual_review_required",
    reason: "Apple student URLs imported; deadlines and eligibility require review.",
    recordsSeen: 4,
    recordsSaved: 3,
  },
  {
    id: "att-devpost-001",
    sourceId: "src-devpost",
    attemptedAt: importedAt,
    status: "manual_review_required",
    reason: "Hackathon URLs imported; dates, prize details, and eligibility require review.",
    recordsSeen: 5,
    recordsSaved: 5,
  },
  {
    id: "att-mlh-001",
    sourceId: "src-mlh",
    attemptedAt: importedAt,
    status: "manual_review_required",
    reason: "MLH event and fellowship links imported; program terms pending verification.",
    recordsSeen: 3,
    recordsSaved: 3,
  },
  {
    id: "att-linkedin-001",
    sourceId: "src-linkedin",
    attemptedAt: "2026-06-27T08:18:00-07:00",
    status: "blocked",
    reason: "Login requirement and platform restrictions.",
    recordsSeen: 0,
    recordsSaved: 0,
  },
  {
    id: "att-x-001",
    sourceId: "src-x",
    attemptedAt: "2026-06-27T08:06:00-07:00",
    status: "blocked",
    reason: "Anti-bot protections and legal restrictions.",
    recordsSeen: 0,
    recordsSaved: 0,
  },
  {
    id: "att-yc-001",
    sourceId: "src-yc",
    attemptedAt: "2026-06-27T08:22:00-07:00",
    status: "manual_review_required",
    reason: "JavaScript-only rendering detected. No opportunity data was inferred.",
    recordsSeen: 0,
    recordsSaved: 0,
  },
];

export const opportunities: Opportunity[] = [
  candidate({
    id: "opp-claude-corps-fellowship",
    title: "Claude Corps Fellowship",
    organization: "Anthropic",
    type: "fellowship",
    sourceId: "src-anthropic",
    url: "https://www.anthropic.com/claude-corps/fellow",
    eligibility: "Official Claude Corps eligibility requires manual verification.",
    source: 0.9,
    extraction: 0.68,
    freshness: 0.78,
  }),
  candidate({
    id: "opp-anthropic-greenhouse-5023394008",
    title: "Anthropic Greenhouse Role 5023394008",
    organization: "Anthropic",
    type: "internship",
    sourceId: "src-anthropic",
    url: "https://job-boards.greenhouse.io/anthropic/jobs/5023394008",
    eligibility: "Role title, student fit, and eligibility require official page review.",
    extraction: 0.42,
    duplicateProbability: 0.24,
  }),
  candidate({
    id: "opp-apple-product-design-undergrad",
    title: "Product Design Undergrad Internships",
    organization: "Apple",
    type: "internship",
    sourceId: "src-apple-students",
    url: "https://jobs.apple.com/en-us/details/200664000-3810/product-design-undergrad-internships",
    eligibility: "Undergraduate internship eligibility requires Apple source review.",
    source: 0.92,
    extraction: 0.74,
    freshness: 0.8,
    duplicateProbability: 0.12,
  }),
  candidate({
    id: "opp-apple-business-marketing-creative-undergrad",
    title: "Business, Marketing, and Creative Undergrad Internships",
    organization: "Apple",
    type: "internship",
    sourceId: "src-apple-students",
    url: "https://jobs.apple.com/en-us/details/200664241-3810/business-marketing-creative-undergrad-internships?team=STDNT",
    eligibility: "Undergraduate internship eligibility requires Apple source review.",
    source: 0.92,
    extraction: 0.74,
    freshness: 0.8,
    duplicateProbability: 0.12,
  }),
  candidate({
    id: "opp-apple-epm-undergrad",
    title: "Engineering Program Management Undergrad Internships",
    organization: "Apple",
    type: "internship",
    sourceId: "src-apple-students",
    url: "https://jobs.apple.com/en-us/details/200664330-3810/engineering-program-management-undergrad-internships?team=STDNT",
    eligibility: "Undergraduate internship eligibility requires Apple source review.",
    source: 0.92,
    extraction: 0.74,
    freshness: 0.8,
    duplicateProbability: 0.12,
  }),
  candidate({
    id: "opp-microsoft-students",
    title: "Microsoft Student Programs",
    organization: "Microsoft",
    type: "student-community",
    sourceId: "src-microsoft-students",
    url: "https://careers.microsoft.com/v2/global/en/students",
    eligibility: "Student program categories require review from the Microsoft students page.",
    source: 0.88,
    extraction: 0.55,
    freshness: 0.76,
    duplicateProbability: 0.2,
  }),
  candidate({
    id: "opp-nvidia-893395492167",
    title: "NVIDIA Career Role 893395492167",
    organization: "NVIDIA",
    type: "internship",
    sourceId: "src-nvidia",
    url: "https://jobs.nvidia.com/careers/job/893395492167",
    eligibility: "Role title, student fit, and eligibility require official page review.",
    extraction: 0.4,
  }),
  candidate({
    id: "opp-cloudflare-greenhouse-7462802",
    title: "Cloudflare Greenhouse Role 7462802",
    organization: "Cloudflare",
    type: "internship",
    sourceId: "src-cloudflare",
    url: "https://job-boards.greenhouse.io/cloudflare/jobs/7462802",
    eligibility: "Role title, student fit, and eligibility require official page review.",
    extraction: 0.4,
    duplicateProbability: 0.22,
  }),
  candidate({
    id: "opp-cloudflare-early-talent",
    title: "Cloudflare Early Talent Roles",
    organization: "Cloudflare",
    type: "student-community",
    sourceId: "src-cloudflare",
    url: "https://www.cloudflare.com/careers/jobs/?department=Early+Talent",
    eligibility: "Early talent filters and open roles require Cloudflare source review.",
    source: 0.88,
    extraction: 0.52,
    duplicateProbability: 0.28,
  }),
  candidate({
    id: "opp-samsara-7839203",
    title: "Samsara Career Role 7839203",
    organization: "Samsara",
    type: "internship",
    sourceId: "src-samsara",
    url: "https://www.samsara.com/company/careers/roles/7839203?gh_jid=7839203",
    eligibility: "Role title, student fit, and eligibility require official page review.",
    source: 0.82,
    extraction: 0.38,
  }),
  candidate({
    id: "opp-cohere-bebee-swe-intern-2026",
    title: "Software Engineer Intern, Spring/Summer 2026",
    organization: "Cohere via BeBee",
    type: "internship",
    sourceId: "src-bebee",
    location: "San Francisco, CA",
    url: "https://bebee.com/us/jobs/software-engineer-intern-spring-summer-2026-cohere-san-francisco-ca--theirstack-676643934",
    eligibility: "Aggregator listing must be reconciled with an official Cohere posting.",
    source: 0.48,
    extraction: 0.58,
    freshness: 0.48,
    duplicateProbability: 0.32,
    evidence: [chatImportEvidence, aggregatorEvidence],
  }),
  candidate({
    id: "opp-jobright-69fecb6",
    title: "Jobright Candidate Opportunity 69fecb6",
    organization: "Manual review",
    type: "internship",
    sourceId: "src-jobright",
    url: "https://jobright.ai/jobs/info/69fecb6aae08e368e37a10c6",
    eligibility: "Aggregator-only record; employer, role, and student fit require review.",
    source: 0.42,
    extraction: 0.28,
    freshness: 0.45,
    duplicateProbability: 0.34,
    evidence: [chatImportEvidence, aggregatorEvidence],
  }),
  candidate({
    id: "opp-la-hacks-ai",
    title: "LA Hacks AI",
    organization: "LA Hacks",
    type: "hackathon",
    sourceId: "src-devpost",
    url: "https://ai.lahacks.com/",
    eligibility: "Hackathon dates, prizes, and participant eligibility require official review.",
    source: 0.8,
    extraction: 0.62,
    freshness: 0.7,
    evidence: [chatImportEvidence],
  }),
  candidate({
    id: "opp-ai-builders-hackathon-2026",
    title: "AI Builders Hackathon 2026",
    organization: "Devpost",
    type: "hackathon",
    sourceId: "src-devpost",
    url: "https://ai-builders-hackathon-2026.devpost.com/",
    eligibility: "Hackathon dates, prizes, and participant eligibility require official review.",
    source: 0.78,
    extraction: 0.64,
    freshness: 0.7,
    duplicateProbability: 0.16,
    evidence: [chatImportEvidence],
  }),
  candidate({
    id: "opp-neural-sprint",
    title: "Neural Sprint",
    organization: "Devpost",
    type: "hackathon",
    sourceId: "src-devpost",
    url: "https://neuralsprint.devpost.com/",
    eligibility: "Hackathon dates, prizes, and participant eligibility require official review.",
    source: 0.78,
    extraction: 0.64,
    freshness: 0.7,
    duplicateProbability: 0.16,
    evidence: [chatImportEvidence],
  }),
  candidate({
    id: "opp-reverie-hacks-2026",
    title: "Reverie Hacks 2026",
    organization: "Devpost",
    type: "hackathon",
    sourceId: "src-devpost",
    url: "https://reverie-hacks-2026.devpost.com/",
    eligibility: "Hackathon dates, prizes, and participant eligibility require official review.",
    source: 0.78,
    extraction: 0.64,
    freshness: 0.7,
    duplicateProbability: 0.16,
    evidence: [chatImportEvidence],
  }),
  candidate({
    id: "opp-pixel-forge-ai-hackathon",
    title: "Pixel Forge AI Hackathon",
    organization: "Devpost",
    type: "hackathon",
    sourceId: "src-devpost",
    url: "https://pixel-forge-ai-hackathon-08.devpost.com/",
    eligibility: "Hackathon dates, prizes, and participant eligibility require official review.",
    source: 0.78,
    extraction: 0.64,
    freshness: 0.7,
    duplicateProbability: 0.16,
    evidence: [chatImportEvidence],
  }),
  candidate({
    id: "opp-mlh-global-hack-week-agents",
    title: "Global Hack Week: Agents",
    organization: "Major League Hacking",
    type: "hackathon",
    sourceId: "src-mlh",
    url: "https://events.mlh.com/events/14312-global-hack-week-agents",
    eligibility: "Event dates and participant eligibility require MLH source review.",
    source: 0.86,
    extraction: 0.66,
    freshness: 0.76,
  }),
  candidate({
    id: "opp-mlh-2026-events",
    title: "MLH 2026 Events",
    organization: "Major League Hacking",
    type: "hackathon",
    sourceId: "src-mlh",
    url: "https://www.mlh.com/seasons/2026/events",
    eligibility: "Season event list needs event-level review before reporting specific dates.",
    source: 0.86,
    extraction: 0.52,
    freshness: 0.76,
    duplicateProbability: 0.3,
  }),
  candidate({
    id: "opp-mlh-fellowship",
    title: "MLH Fellowship",
    organization: "Major League Hacking",
    type: "fellowship",
    sourceId: "src-mlh",
    url: "https://fellowship.mlh.com/",
    eligibility: "Fellowship tracks, dates, and eligibility require MLH source review.",
    source: 0.86,
    extraction: 0.62,
    freshness: 0.76,
    duplicateProbability: 0.16,
  }),
];

export const reviewQueue: ReviewItem[] = [
  {
    id: "rev-chat-import",
    sourceId: "src-chatgpt-share",
    status: "pending",
    reason:
      "Shared ChatGPT conversation provided candidate URLs, not verified scraped fields. Confirm every imported record against its source before approval.",
    queuedAt: importedAt,
    fields: {
      eligibility: "Verify official source before publishing.",
      deadline: "Manual review",
      compensation: "Manual review",
    },
    attachments: [{ id: "file-chat-001", kind: "screenshot", name: "chatgpt-share-import.html" }],
    aiExtractionOverride:
      "Use this queue item to override extracted titles, merge duplicates, or reject links that are no longer open.",
  },
  {
    id: "rev-anthropic-claude-corps",
    opportunityId: "opp-claude-corps-fellowship",
    sourceId: "src-anthropic",
    status: "pending",
    reason:
      "Claude Corps was the main conversation signal. Verify deadline, compensation, eligibility, location, and whether the Greenhouse role is a duplicate.",
    queuedAt: importedAt,
    fields: {
      deadline: "Manual review",
      compensation: "Manual review",
      eligibility: "Official Claude Corps eligibility requires manual verification.",
    },
    attachments: [],
    duplicateOf: "opp-anthropic-greenhouse-5023394008",
  },
  {
    id: "rev-apple-undergrad",
    opportunityId: "opp-apple-product-design-undergrad",
    sourceId: "src-apple-students",
    status: "pending",
    reason:
      "Apple imported three undergrad internship URLs. Confirm locations, team-specific eligibility, deadlines, and whether search-page records should merge.",
    queuedAt: importedAt,
    fields: {
      deadline: "Manual review",
      compensation: "Manual review",
    },
    attachments: [],
  },
  {
    id: "rev-company-roles",
    opportunityId: "opp-nvidia-893395492167",
    sourceId: "src-nvidia",
    status: "pending",
    reason:
      "NVIDIA, Cloudflare, and Samsara role IDs were imported without reliable titles. Review official pages before displaying as verified internships.",
    queuedAt: importedAt,
    fields: {
      title: "Manual review",
      deadline: "Manual review",
      compensation: "Manual review",
    },
    attachments: [],
  },
  {
    id: "rev-devpost-hackathons",
    opportunityId: "opp-ai-builders-hackathon-2026",
    sourceId: "src-devpost",
    status: "pending",
    reason:
      "Devpost and LA Hacks URLs need official date, deadline, prize, team-size, and student eligibility checks.",
    queuedAt: importedAt,
    fields: {
      deadline: "Manual review",
      compensation: "Manual review",
    },
    attachments: [],
  },
  {
    id: "rev-mlh-programs",
    opportunityId: "opp-mlh-fellowship",
    sourceId: "src-mlh",
    status: "pending",
    reason:
      "MLH events and fellowship links may overlap. Merge event-list records into specific opportunities after official review.",
    queuedAt: importedAt,
    fields: {
      deadline: "Manual review",
      eligibility: "MLH program terms require direct verification.",
    },
    attachments: [],
  },
  {
    id: "rev-aggregators",
    opportunityId: "opp-cohere-bebee-swe-intern-2026",
    sourceId: "src-bebee",
    status: "pending",
    reason:
      "BeBee and Jobright are aggregator-only sources. Do not approve until matched to official employer postings.",
    queuedAt: importedAt,
    fields: {
      deadline: "Manual review",
      compensation: "Manual review",
      eligibility: "Official employer source required.",
    },
    attachments: [],
    duplicateOf: "opp-jobright-69fecb6",
  },
  {
    id: "rev-linkedin-blocked",
    sourceId: "src-linkedin",
    status: "pending",
    reason:
      "Source remains blocked by login and platform restrictions. Continue monitoring only through approved APIs or manual review.",
    queuedAt: "2026-06-27T08:18:00-07:00",
    fields: {},
    attachments: [],
  },
  {
    id: "rev-yc-js",
    sourceId: "src-yc",
    status: "pending",
    reason:
      "YC source rendered with JavaScript-only content in the current adapter. No inferred records were created.",
    queuedAt: "2026-06-27T08:22:00-07:00",
    fields: {},
    attachments: [{ id: "file-yc-001", kind: "screenshot", name: "yc-empty-render.png" }],
  },
];

export const report: DailyReport = {
  id: "rep-2026-06-28",
  date: "2026-06-28",
  week: "2026-W26",
  previousReportDate: "2026-06-27",
  previousReportWeek: "2026-W26",
  generatedFrom: "database",
  changes: [
    {
      id: "chg-001",
      kind: "new",
      opportunityId: "opp-claude-corps-fellowship",
      title: "Claude Corps Fellowship",
      after:
        "Imported from shared ChatGPT conversation as a review-required official Anthropic opportunity.",
    },
    {
      id: "chg-002",
      kind: "new",
      opportunityId: "opp-apple-product-design-undergrad",
      title: "Apple Undergrad Internship Group",
      after:
        "Three Apple undergraduate internship URLs added with manual review required for deadline, compensation, eligibility, and location.",
    },
    {
      id: "chg-003",
      kind: "new",
      opportunityId: "opp-ai-builders-hackathon-2026",
      title: "AI Hackathon Import Group",
      after:
        "LA Hacks AI, AI Builders, Neural Sprint, Reverie Hacks, and Pixel Forge AI saved as hackathon candidates.",
    },
    {
      id: "chg-004",
      kind: "new",
      opportunityId: "opp-mlh-fellowship",
      title: "MLH Programs",
      after:
        "MLH Fellowship, MLH 2026 Events, and Global Hack Week: Agents added for official program review.",
    },
    {
      id: "chg-005",
      kind: "changed",
      opportunityId: "opp-nvidia-893395492167",
      title: "Company Career Role IDs",
      after:
        "NVIDIA, Cloudflare, Samsara, and Anthropic role IDs preserved with unknown fields instead of fabricated details.",
    },
    {
      id: "chg-006",
      kind: "changed",
      opportunityId: "opp-cohere-bebee-swe-intern-2026",
      title: "Aggregator-only Listings",
      after:
        "BeBee and Jobright links flagged as low-confidence manual review records pending official employer confirmation.",
    },
    {
      id: "chg-007",
      kind: "changed",
      opportunityId: "opp-microsoft-students",
      title: "Microsoft Student Programs",
      after:
        "Student program landing page added as a review-required source record rather than a scraped opportunity feed.",
    },
  ],
};
